bankproject/bankapp/urls.py
from django.urls import path

from bankapp import views
app_name='bank'
urlpatterns = [

    path('',views.index,name='index'),
    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('logout',views.logout,name='logout'),
    path('details',views.details,name='details'),
    path('add',views.Add_Details,name='add'),
    path('<int:pk>/', views.Update_view, name='details_change'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'), # AJAX
    # path('add',views.AddDetailsView.as_view(),name='add'),
    # path('ajax-load-branches',views.load_branches, name='ajax_load_branches'),

]

bankproject/bankproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bankproject/bankapp/models.py
from django.db import models

# Create your models here.
class District(models.Model):
    name=models.CharField(max_length=250,unique=True,blank=False)
    district_link=models.TextField()


    def __str__(self):
        return self.name

class Banks(models.Model):
    district=models.ForeignKey(District,on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    class Meta:
        ordering=("district",)
        verbose_name='Bank'
        verbose_name_plural='Banks'

    def __str__(self):
        return self.name

class Account(models.Model):
    account_type=models.CharField(max_length=25,blank=False)
    class Meta:
        ordering=('account_type',)

    def __str__(self):
        return self.account_type
class Details(models.Model):
    name=models.CharField(max_length=250, blank=False)
    dob=models.DateField(max_length=8)
    age=models.IntegerField()
    gender=models.CharField(max_length=10)
    pnumber=models.CharField(max_length=13)
    mailid=models.EmailField()
    address=models.TextField(max_length=250)
    district=models.ForeignKey(District,on_delete=models.SET_NULL,null=True)
    branch=models.ForeignKey(Banks,on_delete=models.SET_NULL,null=True)
    # banks=models.ForeignKey(Banks,on_delete=models.CASCADE)
    account_type=models.ForeignKey(Account,on_delete=models.CASCADE)
    debit_card=models.BooleanField(default=False)
    credits_card=models.BooleanField(default=False)
    online_banking=models.BooleanField(default=False)

    class Meta:
        ordering=('name',)
        verbose_name='Detail'
        verbose_name_plural='Details'

    def __str__(self):
        return self.name

bankproject/bankapp/forms.py
from django import forms
from django.forms import DateInput

from . models import Details,Banks


class DetailsForm(forms.ModelForm):
    class Meta:
        model= Details
        fields= ('name','dob',
                'age','gender',
                'pnumber','mailid',
                'address','district','branch',
                'account_type','debit_card',
                'credits_card','online_banking')

        labels = {'dob': ('D.O.B'),
                    }
        widgets = {
                    'dob': DateInput(attrs={'type': 'date'})
                    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['branch'].queryset = Banks.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['branch'].queryset = Banks.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['branch'].queryset = self.instance.district.branch_set.order_by('name')

    # def __int__(self,*args,**kwargs):
    #     super().__init__(*args,**kwargs)
    #     self.fields['branch'].queryset=Banks.objects.none()
    #
    #     if 'district' in self.data:
    #         try:
    #             district_id = int(self.data.get('district'))
    #             self.fields['branch'].queryset = Banks.objects.filter(district_id=district_id).order_by('branch')
    #         except (ValueError, TypeError):
    #             pass  # invalid input from the client; ignore and fallback to empty City queryset
    #     elif self.instance.pk:
    #         self.fields['branch'].queryset = self.instance.district.branch_set.order_by('branch')

bankproject/bankapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from django.urls import reverse, reverse_lazy

from .models import District,Details,Banks
from . forms import DetailsForm
from django.views.generic.edit import CreateView

# Create your views here.
def index(request):
    district_details= District.objects.all()


    return render(request,"home.html",{'district':district_details})

def login(request):
    district_details = District.objects.all()

    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect("bank:details")
        else:
            messages.info(request,"Invalid username or password")
            return redirect('bank:login')

    return render(request,'login.html',{'district':district_details})

def register(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        cpassword=request.POST['cpassword']

        if password==cpassword:

            if User.objects.filter(username=username).exists():
                messages.info(request,"Username already taken")
                return redirect('register')
            else:
                user=User.objects.create_user(username=username,password=password)
                user.save();
                messages.info(request, "Password Mismatch")
                return redirect('bank:login')
        else:
            messages.info(request, "Password Mismatch")
            return redirect("register")



    return render(request,'register.html')

def logout(requests):
    auth.logout(requests)
    return redirect("/")

def details(request):
    district_details=District.objects.all()
    return render(request, 'details.html', {'district': district_details})

def Add_Details(request):
    form = DetailsForm()
    if request.method == 'POST':
        form = DetailsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('bank:add')
    return render(request, 'add.html', {'form': form})

def Update_view(request, pk):
    person = get_object_or_404(Details, pk=pk)
    form = DetailsForm(instance=details)
    if request.method == 'POST':
        form = DetailsForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            return redirect('details_change', pk=pk)
    return render(request, 'add.html', {'form': form})

# AJAX
def load_cities(request):
    district_id = request.GET.get('district_id')
    branches = Banks.objects.filter(district_id=district_id).all()
    return render(request, 'city_dropdown_list_options.html', {'branches': branches})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)


# class PreviewView(ListView):
#     model = Details
#     context_object_name = 'details'


# class AddDetailsView(CreateView):
#     model = Details
#     form_class = DetailsForm
#     template_name = 'add.html'
#     # success_url = reverse_lazy('add')

# def load_branches(request):
#     district_id = request.GET.get('district')
#     branch = Banks.objects.filter(district_id=district_id).order_by('branch')
#     return render(request, 'branch_dropdown.html', {'branch': branch})

bankproject/templates/add.html
<{% extends 'base.html' %}
{% load static %}
{% block title %}
Add Details
{% endblock %}


{% block content %}

<form method="post" id="personForm" data-cities-url="{% url 'bank:ajax_load_cities' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_district").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const districtId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'district_id': districtId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_branch").html(data);  // replace the contents of the city input with the data that came from the server

                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
</script>



{% endblock %}

bankproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <link rel="icon" href="{% static 'images/bank logo.jpg' %}" type="{% static 'image/gif' %}" />
<!--  <meta name="keywords" content="" />-->
<!--  <meta name="description" content="" />-->

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap" rel="stylesheet" />

  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

  <title>{% block title %}{% endblock %}</title>


</head>
<body>
{% include 'header.html' %}
{% include 'nav.html'%}
{% block content %}
{% endblock %}
{% include 'footer.html' %}

<!-- jQery -->
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <!-- custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
  <!-- End Google Map -->
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

bankproject/templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.name }}</option>
{% endfor %}

bankproject/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Login
{% endblock %}


{% block content %}
<div class="row m-2">
    <div class="container">
        <a href="{% url 'bank:add' %}" class="btn btn-primary">Form</a>
    </div>



<!--</div>-->
<!--<div class="row m-2">-->
<!--    <div class="container">-->
<!--        <div class="col-sm-9 col-md-9 col-lg-9">-->
<!--            <form>-->
<!--              <div class="mb-3">-->
<!--                <label for="exampleInputEmail1" class="form-label">Name</label>-->
<!--                <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="name">-->
<!--&lt;!&ndash;                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>&ndash;&gt;-->
<!--              </div>-->
<!--              <div class="mb-3">-->
<!--                <label for="exampleInputPassword1" class="form-label">DOB</label>-->
<!--                <input type="date" class="form-control" id="exampleInputPassword1" name="dob">-->
<!--              </div>-->
<!--              <div class="mb-3">-->
<!--                <label for="exampleInputPassword1" class="form-label">Age</label>-->
<!--                <input type="number" class="form-control" id="exampleInputPassword1" name="age">-->
<!--              </div>-->
<!--              <div class="mb-3">-->
<!--                <label for="exampleInputPassword1" class="form-label">Gender</label>-->
<!--                <input type="text" class="form-control" id="exampleInputPassword1" name="gender">-->
<!--              </div>-->
<!--              <div class="mb-3">-->
<!--                <label for="exampleInputPassword1" class="form-label">Ph Number</label>-->
<!--                <input type="text" class="form-control" id="exampleInputPassword1" name="pnumber">-->
<!--              </div>-->
<!--              <div class="mb-3">-->
<!--                <label for="exampleInputPassword1" class="form-label">Email</label>-->
<!--                <input type="email" class="form-control" id="exampleInputPassword1" name="mailid">-->
<!--              </div>-->
<!--               <div class="mb-3">-->
<!--                <label for="exampleInputPassword1" class="form-label">Address</label>-->
<!--                <input type="text" class="form-control" id="exampleInputPassword1" name="address">-->
<!--              </div>-->


<!--              <div class="mb-3">-->

<!--                <div class="dropdown">-->
<!--                  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--                    Select District-->
<!--                  </button>-->

<!--                  <ul class="dropdown-menu">-->
<!--                    {% for i in district %}-->
<!--                    <li><a class="dropdown-item" href="#" name="district">{{i.district_name}}</a></li>-->
<!--                    {% endfor %}-->
<!--                  </ul>-->

<!--                </div>-->
<!--              </div>-->
<!--                <div class="mb-3">-->
<!--                <label for="exampleInputPassword1" class="form-label">Branches</label>-->
<!--                <div class="dropdown">-->
<!--                  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--                    Select Branch-->
<!--                  </button>-->
<!--                  <ul class="dropdown-menu">-->
<!--                    <li><a class="dropdown-item" href="#" name="branch">Action</a></li>-->

<!--                  </ul>-->
<!--                </div>-->
<!--              </div>-->
<!--              <div class="row m-1">-->
<!--                <select class="form-select" aria-label="Default select example" name="account_type">-->
<!--                  <option selected>Services</option>-->
<!--                  <option value="1">Savings Account</option>-->
<!--                  <option value="2">Current Account</option>-->
<!--                  <option value="3">Credit Account</option>-->
<!--                </select>-->
<!--              </div>-->
<!--              <div class="form-check form-check-inline">-->
<!--                <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">-->
<!--                <label class="form-check-label" for="inlineCheckbox1">Debit card</label>-->
<!--              </div>-->
<!--              <div class="form-check form-check-inline">-->
<!--                <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="option2">-->
<!--                <label class="form-check-label" for="inlineCheckbox2">Credit Card</label>-->
<!--              </div>-->
<!--              <div class="form-check form-check-inline">-->
<!--                <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3">-->
<!--                <label class="form-check-label" for="inlineCheckbox3">Cheque book</label>-->
<!--              </div>-->



<!--              <button type="submit" class="btn btn-primary">Submit</button>-->
<!--            </form>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

{% endblock %}

bankproject/templates/footer.html
{% load static %}

 <footer class="footer_section">
    <div class="padding-bottom: 2px">
     <div class="container">

      <p>
        &copy; All Rights Reserved By Toni_project</a>
      </p>
     </div>
    </div>
  </footer>

bankproject/templates/header.html
{% load static %}
<header class="header_section long_section px-0">
    <span>
            <img src="{% static 'images/bank logo.jpg' %}" alt="logo" width="300px" height="100px">

    </span>

</header>

bankproject/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Home
{% endblock %}


{% block content %}

<div class="container">
                <div class="row m-5">
                  <div class="col-md-4 col-lg-4">

                      <div class="detail-box ">
                        <h1><br>
                          For All Your <br>
                          Banking Needs
                       </h1>
                        <p><br>
                          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minus quidem maiores perspiciatis, illo maxime voluptatem a itaque suscipit.
                        </p><br>
<!--                    <div class="btn-box">-->
<!--                      <a href="" class="btn1">-->
<!--                        Contact Us-->
<!--                      </a>-->
                          <button type="button" class="btn btn-primary">Contact Us</button>
                          <button type="button" class="btn btn-success">About Us</button>
<!--                      <a href="" class="btn2">-->
<!--                        About Us-->
<!--                      </a>-->
                      </div>

                  </div>

                  <div class="col-md-6 col-lg-6">
                    <div class="img-box">
                      <img src="{% static 'images/online banking.jpg' %}" alt="online-banking image" width="750" height="450" >
                    </div>
                  </div>
                </div>
              </div>

 <!-- about section -->

  <section class="about_section layout_padding long_section">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="img-box">
            <img src="images/about-img.png" alt="">
          </div>
        </div>
        <div class="col-md-6">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                About Us
              </h2>
            </div>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti dolorem eum consequuntur ipsam repellat dolor soluta aliquid laborum, eius odit consectetur vel quasi in quidem, eveniet ab est corporis tempore.
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->
<section class="contact_section  long_section">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="form_container">
            <div class="heading_container">
              <h2>
                Contact Us
              </h2>
            </div>
            <form action="">
              <div>
                <input type="text" placeholder="Your Name" />
              </div>
              <div>
                <input type="text" placeholder="Phone Number" />
              </div>
              <div>
                <input type="email" placeholder="Email" />
              </div>
              <div>
                <input type="text" class="message-box" placeholder="Message" />
              </div>
              <div class="btn_box">
                <button>
                  SEND
                </button>
              </div>
            </form>
          </div>
        </div>
        <div class="col-md-6">
          <div class="map_container">
            <div class="map">
              <div id="googleMap"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- end contact section -->

  <!-- info section -->
  <section class="info_section long_section">

    <div class="container">
      <div class="contact_nav">
        <a href="">
          <i class="fa fa-phone" aria-hidden="true"></i>
          <span>
            Call : +91484 1234567
          </span>
        </a>
        <a href="">
          <i class="fa fa-envelope" aria-hidden="true"></i>
          <span>
            Email : taskbank@bank.com
          </span>
        </a>
        <a href="">
          <i class="fa fa-map-marker" aria-hidden="true"></i>
          <span>
            Location
          </span>
        </a>
      </div>

      <div class="info_top ">
        <div class="row ">
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="info_links">
              <h4>
                QUICK LINKS
              </h4>
              <div class="info_links_menu">
                <a class="" href="index.html">Home <span class="sr-only">(current)</span></a>
                <a class="" href="about.html"> About</a>
                <a class="" href="furniture.html">Service</a>
                <a class="" href="blog.html">Branches</a>
                <a class="" href="contact.html">Contact Us</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock%}

bankproject/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Login
{% endblock %}

{% block content %}
<div class="container">
    <div class="row m-5">
        <div class="col-sm-6 col-md-6 col-lg-6">

           <form method="post">
               {% csrf_token %}
               <div class="form-group">
                    <label for="exampleInputEmail1">User Name</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Username" name="username">

               </div>
               <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
               </div>
<!--               <div class="form-check">-->
<!--                    <input type="checkbox" class="form-check-input" id="exampleCheck1">-->
<!--                    <label class="form-check-label" for="exampleCheck1">Check me out</label>-->
<!--               </div>-->
                    <button type="submit" class="btn btn-primary">Login</button>
                    <a href="{% url 'bank:register' %}" class="btn btn-secondary">Register</a>
           </form>
        </div>
    </div>
</div>


{% endblock %}

bankproject/templates/nav.html
{% load static %}

<div class="col-md-12 col-lg-12">
   <nav class="navbar navbar-expand-lg bg-body-tertiary ">
    <div class="container-fluid">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">
            <ul class="navbar-nav  ">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'bank:index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
               {% if user.is_authenticated %}

                <li class="nav-item">
                <a class="nav-link" href=" "> Bank Accounts</a>
              </li>
                <li class="nav-item">
               <a class="nav-link" >{{user.username}} Account</a>
              </li>
                 {% else %}
              <li class="nav-item">

                <a class="nav-link" href="{% url 'bank:login' %} "> Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href=" {% url 'bank:register' %}">Register</a>
              </li>
                {% endif %}

<!--              <li class="nav-item dropdown {% if 'bankapp' in request.path %}active{% endif %}" >-->
<!--                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--                    Dropdown-->
<!--                  </a>-->
<!--                  <ul class="dropdown-menu">-->

<!--                    {% for i in district %}-->
<!--                    <li><a class="dropdown-item" href="{{i.district_link}}">{{i.district_name}}</a></li>-->
<!--                    {% endfor %}-->
<!--                  </ul>-->
<!--              </li>-->

              <li class="nav-item">
<!--                <a class="nav-link" href=" ">Branches</a>-->
                <div class="dropdown">
                  <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Districts
                  </button>
                  <ul class="dropdown-menu">
                    {% for i in district %}
                    <li><a class="dropdown-item" href="{{i.district_link}}">{{i.name}}</a></li>

                     {% endfor %}
<!--&lt;!&ndash;                    <li><a class="dropdown-item" href="#">Another action</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;                    <li><a class="dropdown-item" href="#">Something else here</a></li>&ndash;&gt;-->
                  </ul>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href=" ">Services</a>
              </li>
            </ul>
          </div>
            {% if user.is_authenticated %}
            <ul class ="nav-item">Hello {{user.username}} </ul>

            <div class="quote_btn-container">
               <ul> <a href="{% url 'bank:logout' %}">
              <span>
                Logout
              </span>
            </a></ul>
            {% else %}
          <div class="quote_btn-container">
            <a href="{% url 'bank:login' %}">
              <span>
                Login
              </span>
              <i class="fa fa-user" aria-hidden="true"></i>
            </a>
              {% endif %}
            <form class="form-inline">
              <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                <i class="fa fa-search" aria-hidden="true"></i>
              </button>
            </form>
          </div>
        </div>
      </div>

   </nav>

 </div>

bankproject/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Register
{% endblock %}

{% block content %}
<div class="container">
    <div class="row m-5">
        <div class="col-sm-6 col-md-6 col-lg-6">

           <form method="post" action="register">
               {% csrf_token %}
               <div class="form-group">
                    <label for="exampleInputEmail1">User Name</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Username" name="username">

               </div>
               <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
               </div>
               <div class="form-group">
                    <label for="exampleInputPassword1">Confirm Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Confirm Password" name="cpassword">
               </div>
<!--               <div class="form-check">-->
<!--                    <input type="checkbox" class="form-check-input" id="exampleCheck1">-->
<!--                    <label class="form-check-label" for="exampleCheck1">Check me out</label>-->
<!--               </div>-->
                    <button type="submit" class="btn btn-primary">Submit</button>

           </form>
            {% for msg in messages %}
            {{msg}}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}